# Site settings
name: ChangHyeon-In
email: dlsckdgus88@gmail.com
author: ChangHyeon In
url: changhyeon-in.github.io
resume_site:
github: https://github.com/ChangHyeon-In/
baseurl:
description: Actually, less is more!
meta_description: Test Page
motto: It's our wits that make us men.
banner: Test

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: ChangHyeon-In

# Build settings
markdown: kramdown
disqus-shortname: ChangHyeon-In